### ISSUE TITLE
Request - Hearthstone Hotkey and Configurable Timer

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Sythiex/Hearthstone_Mod#1]
Request a hearthstone hotkey rather than an item.

**Comment by Sythiex** [comment]
A hotkey probably won't happen as the mod is balanced around the hearthstone being an item for survival. For non-item teleportation, mods like JourneyMap handle it very well. The timers for both the channel time and cooldown can be modified in the config file for the mod.
