### ISSUE TITLE
Crash when using with Twilight Forest

### ISSUE THREAD

**Issue by DPattee** [Sythiex/Hearthstone_Mod#2]
I've repro'd this twice.

Set the hearthstone location to my bed in the regular overworld. Hearthstone functions fine anywhere in the overworld.

Enter the Twilight Forest with full health and attempt to use the hearthstone. 

As soon as the timer fires, the loading screen comes up, stays up for a long time, and then I get a server disconnect error message. 

Reconnect to server, immediately start losing health and frantically start digging. You are in the overworld, but you are way down underground in the rocks suffocating. 

Dig a whole fast enough that you don't die. Hearthstone cooldown is already back to 'ready now'. Use hearthstone again, and you teleport to the proper location.

**Comment by Sythiex** [comment]
Issue should be fixed in the latest version. Let me know if you continue to experience this issue.
